<a href="https://colab.research.google.com/github/NaveenOctoninja/Data-Virtualization/blob/main/House_Price_Preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# ======================================================
# HOUSE PRICE DATA PREPROCESSING PROJECT
# ======================================================

# ===========================
# 1. Import Libraries
# ===========================

import pandas as pd
import sqlite3
from google.colab import files

print("Libraries Imported Successfully\n")

# ===========================
# 2. Upload Dataset
# ===========================

print("Upload your 'housing prices.csv' file")
uploaded = files.upload()

# ===========================
# 3. Load Dataset
# ===========================

df = pd.read_csv("housing prices.csv")

print("\nDataset Loaded Successfully!")

# ===========================
# 4. Dataset Information
# ===========================

print("\n==============================")
print("FIRST 5 ROWS")
print("==============================")
display(df.head())

print("\n==============================")
print("LAST 5 ROWS")
print("==============================")
display(df.tail())

print("\nShape of Dataset")
print(df.shape)

print("\nColumns")
print(df.columns.tolist())

print("\nData Types")
print(df.dtypes)

print("\nDataset Information")
df.info()

# ===========================
# 5. Data Cleaning
# ===========================

print("\nCleaning Column Names...")

df.columns = df.columns.str.strip()

print("Column Names After Cleaning")
print(df.columns.tolist())

# ===========================
# 6. Missing Values
# ===========================

print("\n==============================")
print("MISSING VALUES")
print("==============================")

print(df.isnull().sum())

# Fill numerical missing values

df["total_bedrooms"] = df["total_bedrooms"].fillna(
    df["total_bedrooms"].median()
)

print("\nMissing Values After Filling")
print(df.isnull().sum())

# ===========================
# 7. Remove Duplicates
# ===========================

print("\n==============================")
print("DUPLICATE VALUES")
print("==============================")

duplicates = df.duplicated().sum()

print("Duplicate Rows :", duplicates)

df = df.drop_duplicates()

print("Duplicates Removed Successfully!")

print("New Shape :", df.shape)

# ===========================
# 8. Statistical Summary
# ===========================

print("\n==============================")
print("STATISTICAL SUMMARY")
print("==============================")

display(df.describe())

print("\nCategorical Summary")

display(df.describe(include="object"))

# ===========================
# 9. Export CSV
# ===========================

df.to_csv("cleaned_housing_prices.csv", index=False)

print("\nCSV File Created!")

# ===========================
# 10. Export Excel
# ===========================

df.to_excel("cleaned_housing_prices.xlsx", index=False)

print("Excel File Created!")

# ===========================
# 11. Export JSON
# ===========================

df.to_json(
    "cleaned_housing_prices.json",
    orient="records",
    indent=4
)

print("JSON File Created!")

# ===========================
# 12. Export SQL
# ===========================

connection = sqlite3.connect("housing.db")

df.to_sql(
    "housing",
    connection,
    if_exists="replace",
    index=False
)

print("SQLite Database Created!")

# ===========================
# 13. SQL Queries
# ===========================

print("\n==============================")
print("SELECT")
print("==============================")

query = "SELECT * FROM housing LIMIT 5"

display(pd.read_sql(query, connection))

print("\n==============================")
print("WHERE")
print("==============================")

query = """
SELECT *
FROM housing
WHERE median_income > 5
LIMIT 5
"""

display(pd.read_sql(query, connection))

print("\n==============================")
print("ORDER BY")
print("==============================")

query = """
SELECT *
FROM housing
ORDER BY median_house_value DESC
LIMIT 5
"""

display(pd.read_sql(query, connection))

print("\n==============================")
print("GROUP BY")
print("==============================")

query = """
SELECT
ocean_proximity,
AVG(median_house_value) AS AveragePrice
FROM housing
GROUP BY ocean_proximity
"""

display(pd.read_sql(query, connection))

print("\n==============================")
print("COUNT")
print("==============================")

query = """
SELECT COUNT(*) AS TotalRows
FROM housing
"""

display(pd.read_sql(query, connection))

print("\n==============================")
print("AVG")
print("==============================")

query = """
SELECT AVG(median_income) AS AverageIncome
FROM housing
"""

display(pd.read_sql(query, connection))

print("\n==============================")
print("MAX")
print("==============================")

query = """
SELECT MAX(median_house_value) AS HighestPrice
FROM housing
"""

display(pd.read_sql(query, connection))

print("\n==============================")
print("MIN")
print("==============================")

query = """
SELECT MIN(median_house_value) AS LowestPrice
FROM housing
"""

display(pd.read_sql(query, connection))

# ===========================
# 14. Custom SQL Query
# ===========================

print("\n==============================")
print("CUSTOM SQL QUERY")
print("==============================")

query = """
SELECT
ocean_proximity,
COUNT(*) AS NumberOfHouses,
AVG(median_house_value) AS AveragePrice
FROM housing
GROUP BY ocean_proximity
ORDER BY AveragePrice DESC
"""

result = pd.read_sql(query, connection)

display(result)

connection.close()

# ===========================
# 15. Download Files
# ===========================

print("\nDownloading Files...")

files.download("cleaned_housing_prices.csv")
files.download("cleaned_housing_prices.xlsx")
files.download("cleaned_housing_prices.json")
files.download("housing.db")

print("\nPROJECT COMPLETED SUCCESSFULLY!")

Libraries Imported Successfully

Upload your 'housing prices.csv' file

Saving housing prices.csv to housing prices.csv

Dataset Loaded Successfully!

==============================
FIRST 5 ROWS
==============================

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY

==============================
LAST 5 ROWS
==============================

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,INLAND
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,INLAND
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,INLAND
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,INLAND
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,INLAND

Shape of Dataset
(20640, 10)

Columns
['longitude', 'latitude', 'housing_median_age', 'total_rooms', 'total_bedrooms', 'population', 'households', 'median_income', 'median_house_value', 'ocean_proximity']

Data Types
longitude             float64
latitude              float64
housing_median_age    float64
total_rooms           float64
total_bedrooms        float64
population            float64
households            float64
median_income         float64
median_house_value    float64
ocean_proximity        object
dtype: object

Dataset Information
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object
dtypes: float64(9), object(1)
memory usage: 1.6+ MB

Cleaning Column Names...
Column Names After Cleaning
['longitude', 'latitude', 'housing_median_age', 'total_rooms', 'total_bedrooms', 'population', 'households', 'median_income', 'median_house_value', 'ocean_proximity']

==============================
MISSING VALUES
==============================
longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

Missing Values After Filling
longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
median_house_value    0
ocean_proximity       0
dtype: int64

==============================
DUPLICATE VALUES
==============================
Duplicate Rows : 0
Duplicates Removed Successfully!
New Shape : (20640, 10)

==============================
STATISTICAL SUMMARY
==============================

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
count,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000
mean,-119.569704,35.631861,28.639486,2635.763081,536.838857,1425.476744,499.539680,3.870671,206855.816909
std,2.003532,2.135952,12.585558,2181.615252,419.391878,1132.462122,382.329753,1.899822,115395.615874
min,-124.350000,32.540000,1.000000,2.000000,1.000000,3.000000,1.000000,0.499900,14999.000000
25%,-121.800000,33.930000,18.000000,1447.750000,297.000000,787.000000,280.000000,2.563400,119600.000000
50%,-118.490000,34.260000,29.000000,2127.000000,435.000000,1166.000000,409.000000,3.534800,179700.000000
75%,-118.010000,37.710000,37.000000,3148.000000,643.250000,1725.000000,605.000000,4.743250,264725.000000
max,-114.310000,41.950000,52.000000,39320.000000,6445.000000,35682.000000,6082.000000,15.000100,500001.000000

Categorical Summary

       ocean_proximity
count            20640
unique               5
top          <1H OCEAN
freq              9136

CSV File Created!
Excel File Created!
JSON File Created!
SQLite Database Created!

==============================
SELECT
==============================

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY

==============================
WHERE
==============================

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.29,37.82,49.0,135.0,29.0,86.0,23.0,6.1183,75000.0,NEAR BAY

==============================
ORDER BY
==============================

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.27,37.80,52.0,249.0,78.0,396.0,85.0,1.2434,500001.0,NEAR BAY
1,-122.25,37.87,52.0,609.0,236.0,1349.0,250.0,1.1696,500001.0,NEAR BAY
2,-122.24,37.86,52.0,1668.0,225.0,517.0,214.0,7.8521,500001.0,NEAR BAY
3,-122.24,37.85,52.0,3726.0,474.0,1366.0,496.0,9.3959,500001.0,NEAR BAY
4,-122.23,37.83,52.0,2990.0,379.0,947.0,361.0,7.8772,500001.0,NEAR BAY

==============================
GROUP BY
==============================

  ocean_proximity   AveragePrice
0       <1H OCEAN  240084.285464
1          INLAND  124805.392001
2          ISLAND  380440.000000
3        NEAR BAY  259212.311790
4      NEAR OCEAN  249433.977427

==============================
COUNT
==============================

   TotalRows
0      20640

==============================
AVG
==============================

   AverageIncome
0       3.870671

==============================
MAX
==============================

   HighestPrice
0      500001.0

==============================
MIN
==============================

   LowestPrice
0      14999.0

==============================
CUSTOM SQL QUERY
==============================

  ocean_proximity  NumberOfHouses   AveragePrice
0          ISLAND               5  380440.000000
1        NEAR BAY            2290  259212.311790
2      NEAR OCEAN            2658  249433.977427
3       <1H OCEAN            9136  240084.285464
4          INLAND            6551  124805.392001

Downloading Files...

PROJECT COMPLETED SUCCESSFULLY!